  (
  ID           : '';
  Level        : 0;
  Items        : '';
  Creatures    : '';
  Underground  : False;
  Village      : False;
  GenID        : G_DARK_FOREST;
  DecorType    : '';
  DecTypSize   : 0;
  DecTypCount  : 0;
  IsAutoEnt    : False;
  PrevMap      : '';
  NextMap      : '';
  AltNextMap   : '';
  IsAltMapEnt  : False;
  IsVillageEnt : False;
  IsTraps      : False;
  FloorTile    : 'FLOOR';
  FloorRes     : '';
  WallRes      : '';
  )
