  (
  ID           : 'VILLAGE';
  Level        : 0;
  Items        : '';
  Creatures    : '';
  Underground  : False;
  Village      : True;
  GenID        : G_VILLAGE;
  DecorType    : '';
  DecTypSize   : 0;
  DecTypCount  : 0;
  IsAutoEnt    : False;
  PrevMap      : '';
  NextMap      : '';
  AltNextMap   : '';
  IsAltMapEnt  : False;
  IsVillageEnt : True;
  IsTraps      : False;
  FloorTile    : tlGrass;
  FloorRes     : 'DIRTFLOOR0';
  WallRes      : '';
  ),
